config-version: 2

name: 'apple_search_ads_integration_tests'
version: '0.2.2'

profile: 'integration_tests' 

vars:
  apple_search_ads_schema: apple_search_ads_integrations_tests_1
  apple_search_ads_organization_identifier: "organization_data"
  apple_search_ads_campaign_history_identifier: "campaign_history_data"
  apple_search_ads_campaign_report_identifier: "campaign_report_data"
  apple_search_ads_ad_group_history_identifier: "ad_group_history_data"
  apple_search_ads_ad_group_report_identifier: "ad_group_report_data"
  apple_search_ads_ad_history_identifier: "ad_history_data"
  apple_search_ads_ad_report_identifier: "ad_report_data"
  apple_search_ads_keyword_history_identifier: "keyword_history_data"
  apple_search_ads_keyword_report_identifier: "keyword_report_data"
  apple_search_ads_search_term_report_identifier: "search_term_report_data"
  apple_search_ads__using_search_terms: True

seeds:
  +quote_columns: "{{ true if target.type == 'redshift' else false }}"
  apple_search_ads_integration_tests:
    +column_types:
      modification_time: "timestamp"
      start_time: "timestamp"
      end_time: "timestamp"
      creation_time: "timestamp"
      _fivetran_synced: "timestamp"
        
dispatch:
  - macro_namespace: dbt_utils
    search_order: ['spark_utils', 'dbt_utils']